from langchain.tools import tool   # THis will import the "tool" decorator from the langchain.tools module, which is used to create a tool in LangChain.

@tool   #decorator for creating tool 
def get_greeting(name : str) -> str :
    """Generate a Greeting to the user."""   #-----> THis is a "docstring" which is a short description written inside a Python function to explain what the function does.
    return f"Hello {name}, Welcome to the world of AI!"

result = get_greeting.invoke({"name" : "Ritika"})   # Here we are invoking the tool name "get_greeting", with the input parameter "name" set to "Ritika". The tool will generate a greeting message for the user.

print(result)   # It will print the greeting message generated by the tool.

print(get_greeting.name)         # This will print the name of the tool, which is "get_greeting".
print(get_greeting.description)  # This will print the description of the tool, which is "Generate a Greeting to the user."
print(get_greeting.args)         # This will print the arguments of the tool, which is a dictionary containing the argument name "name" and its type "str".